" vim:set fenc=utf8 ff=unix ts=8 sts=2 sw=2 tw=0 fdm=marker:

let s:on_windows = has('win95') || has('win16') || has('win32') || has('win64')

if s:on_windows
  set guifont=MS_Gothic:h10:cSHIFTJIS
  "set guifont=Inconsolata:h10
  set renderoptions=type:directx

  set linespace=0
  set columns=165
  set lines=74
  set cmdheight=2
  set guioptions-=T
  set guioptions-=m
  "set guioptions+=a	" ビジュアルモードで選択したテキストをクリップボードに入れる
  if exists('&transparency')
    set transparency=240
    augroup hack234
      autocmd!
      autocmd GUIEnter * set transparency=240
      autocmd FocusGained * set transparency=240
      autocmd FocusLost * set transparency=210
    augroup END
  endif
  "if has('kaoriya')
  "  " 一部のUCS文字の幅を自動計測して決める
  "  set ambiwidth=auto
  "endif
elseif has('mac')
  set guifont=InconsolataForPowerline:h14
  set columns=100
  set lines=60
  set cmdheight=2
  set guioptions-=T
  set guioptions-=m
  set guioptions+=a
  set transparency=10
  augroup hack234
    autocmd!
    autocmd FocusGained * set transparency=6
    autocmd FocusLost * set transparency=18
  augroup END
elseif has('xfontset')
  set guifontset=a14,r14,k14
endif
